### ISSUE TITLE
Determining offending properties of oneOf with required fields?

### ISSUE THREAD

**Issue by derekcannon** [mirego/activerecord_json_validator#25]
I might be doing something wrong here, but I have two fields, field_a and field_b, and I'm looking for one of them to be set, but not both. Like this:

[x] field_a
[ ] field_b
=> passes

[ ] field_a
[x] field_b
=> passes 

[ ] field_a
[ ] field_b
=> fails

[x] field_a
[x] field_b
=> fails

Here's my schema:

```
schema:
  $schema: http://json-schema.org/draft-04/schema#
  type: object
  properties:
    field_a:
      type: string
    field_b:
      type: string
  oneOf: [
    { required: ['field_a'] },
    { required: ['field_b'] }
  ]
```

The only situation I'm having trouble with is when both field_a and field_b are set. The JSON validator does correctly fail validation, but the error is not descriptive enough to determine the fields triggering the validation error:

```
[{:schema=>#<Addressable::URI:xxxxx URI:xxxxx>,
  :fragment=>"#/",
  :message=>"The property '#/' of type Hash matched more than one of the required schemas in schema xxxxx#",
  :failed_attribute=>"OneOf"}]
```

Is there something I'm doing wrong here?

To contrast between an error dealing with neither field_a nor field_b being set, this is the validation error returned:

```
[{:schema=>#<Addressable::URI:xxxxx URI:xxxxx>,
  :fragment=>"#/",
  :message=>"The property '#/' of type Hash did not match any of the required schemas in schema xxxxx",
  :failed_attribute=>"OneOf",
  :errors=>
   {:oneof_0=>
     [{:schema=>#<Addressable::URI:xxxxx URI:xxxxx>,
       :fragment=>"#/",
       :message=>"The property '#/' did not contain a required property of 'field_a' in schema xxxxx",
       :failed_attribute=>"Required"}],
    :oneof_1=>
     [{:schema=>#<Addressable::URI:xxxxx URI:xxxxx>,
       :fragment=>"#/",
       :message=>"The property '#/' did not contain a required property of 'field_b' in schema xxxxx",
       :failed_attribute=>"Required"}]}}]
```
